[[Qt6Declarative]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03c4955939ba8b9c64d44d99101d344814cd2ecc"
libc = "musl"
os = "linux"

    [[Qt6Declarative.download]]
    sha256 = "f8b32d743d6870ad7d94c724792d7288b099e4aa3330fef58452a24719384a86"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Declarative_jll.jl/releases/download/Qt6Declarative-v6.10.2+0/Qt6Declarative.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
